import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { ContentStatus, Prisma } from "@prisma/client";
import type { AdminPrincipal } from "../admin-auth/auth.types";
import { PrismaService } from "../prisma/prisma.service";
import { PreviewContextService } from "./preview-context.service";
import type { PublishableResource } from "./publishing.types";
const json=(value:unknown)=>JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
@Injectable()
export class PublishingService{
 constructor(private readonly prisma:PrismaService,private readonly previewContext:PreviewContextService){}
 async current(resource:PublishableResource,id:string){let row:unknown;switch(resource){
  case"pages":row=await this.prisma.page.findFirst({where:{id,deletedAt:null},select:{slug:true,title:true,sections:{where:{isEnabled:true},orderBy:{displayOrder:"asc"},select:{key:true,kind:true,content:true,displayOrder:true}},seo:{select:{title:true,description:true,canonicalUrl:true,openGraph:true}}}});break;
  case"services":row=await this.prisma.service.findFirst({where:{id,deletedAt:null},select:{slug:true,name:true,summary:true,content:true,displayOrder:true,seo:{select:{title:true,description:true,canonicalUrl:true,openGraph:true}}}});break;
  case"portfolio":row=await this.prisma.portfolioProject.findFirst({where:{id,deletedAt:null},select:{slug:true,title:true,clientName:true,summary:true,content:true,displayOrder:true,category:{select:{slug:true,name:true}},service:{select:{slug:true,name:true}},seo:{select:{title:true,description:true,canonicalUrl:true,openGraph:true}}}});break;
  case"packages":row=await this.prisma.package.findUnique({where:{id},select:{slug:true,name:true,subtitle:true,description:true,price:true,currency:true,priceLabel:true,isPopular:true,displayOrder:true,category:{select:{slug:true,name:true,headline:true,description:true,content:true}},features:{orderBy:{displayOrder:"asc"},select:{label:true,displayOrder:true}}}});break;
  case"testimonials":row=await this.prisma.testimonial.findUnique({where:{id},select:{clientName:true,clientRole:true,company:true,quote:true,rating:true,displayOrder:true}});break;
 }if(!row)throw new NotFoundException("Publishable content not found");return JSON.parse(JSON.stringify(row)) as Record<string,unknown>}
 async preview(resource:PublishableResource,id:string,admin:AdminPrincipal){await this.current(resource,id);const token=this.previewContext.sign(resource,id,admin.id);return{path:`/preview/${resource}/${id}?token=${encodeURIComponent(token)}`,expiresInSeconds:this.previewContext.ttlSeconds()}}
 async previewData(resource:PublishableResource,id:string,token:string){this.previewContext.verify(token,resource,id);return this.current(resource,id)}
 async revisions(resource:PublishableResource,id:string){return this.prisma.contentRevision.findMany({where:{resource,entityId:id},orderBy:{version:"desc"},select:{id:true,version:true,createdAt:true,publishedAt:true,createdBy:{select:{displayName:true}},publishedBy:{select:{displayName:true}}}})}
 async publish(resource:PublishableResource,id:string,admin:AdminPrincipal){const payload=await this.current(resource,id);return this.prisma.$transaction(async tx=>{const latest=await tx.contentRevision.findFirst({where:{resource,entityId:id},orderBy:{version:"desc"},select:{version:true}});const version=(latest?.version??0)+1;const revision=await tx.contentRevision.create({data:{resource,entityId:id,version,payload:json(payload),createdById:admin.id,publishedById:admin.id,publishedAt:new Date()}});switch(resource){case"pages":await tx.page.update({where:{id},data:{publishedSnapshot:json(payload),status:ContentStatus.PUBLISHED,publishedAt:new Date()}});break;case"services":await tx.service.update({where:{id},data:{publishedSnapshot:json(payload),status:ContentStatus.PUBLISHED}});break;case"portfolio":await tx.portfolioProject.update({where:{id},data:{publishedSnapshot:json(payload),status:ContentStatus.PUBLISHED,publishedAt:new Date()}});break;case"packages":await tx.package.update({where:{id},data:{publishedSnapshot:json(payload),status:ContentStatus.PUBLISHED,isActive:true}});break;case"testimonials":await tx.testimonial.update({where:{id},data:{publishedSnapshot:json(payload),status:ContentStatus.PUBLISHED}});break;}await tx.activityLog.create({data:{actorId:admin.id,action:"CONTENT_PUBLISH",entityType:resource,entityId:id,after:json({version})}});return{published:true,version,revisionId:revision.id}})}
 async unpublish(resource:PublishableResource,id:string,admin:AdminPrincipal){await this.current(resource,id);await this.prisma.$transaction(async tx=>{switch(resource){case"pages":await tx.page.update({where:{id},data:{publishedSnapshot:Prisma.DbNull,status:ContentStatus.DRAFT,publishedAt:null}});break;case"services":await tx.service.update({where:{id},data:{publishedSnapshot:Prisma.DbNull,status:ContentStatus.DRAFT}});break;case"portfolio":await tx.portfolioProject.update({where:{id},data:{publishedSnapshot:Prisma.DbNull,status:ContentStatus.DRAFT,publishedAt:null}});break;case"packages":await tx.package.update({where:{id},data:{publishedSnapshot:Prisma.DbNull,status:ContentStatus.DRAFT}});break;case"testimonials":await tx.testimonial.update({where:{id},data:{publishedSnapshot:Prisma.DbNull,status:ContentStatus.DRAFT}});break;}await tx.activityLog.create({data:{actorId:admin.id,action:"CONTENT_UNPUBLISH",entityType:resource,entityId:id}})});return{unpublished:true}}
 ensureResource(value:string):PublishableResource{if(!(["pages","services","portfolio","packages","testimonials"] as string[]).includes(value))throw new BadRequestException("Unsupported publishable resource");return value as PublishableResource}
}
