import { ValidationPipe } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import { PrismaClient } from "@prisma/client";
import { json } from "express";
import { randomBytes } from "node:crypto";
import { loadEnvFile } from "node:process";
import { resolve } from "node:path";
import { AppModule } from "../src/app.module";
import { ResponseInterceptor } from "../src/common/interceptors/response.interceptor";
loadEnvFile(resolve(__dirname,"../../.env"));
type JsonRecord=Record<string,unknown>;
class CookieJar{private readonly values=new Map<string,string>();apply(response:Response){for(const line of response.headers.getSetCookie()){const[pair]=line.split(";");const separator=pair.indexOf("=");const name=pair.slice(0,separator),value=pair.slice(separator+1);if(value)this.values.set(name,value)}}header(){return[...this.values].map(([name,value])=>`${name}=${value}`).join("; ")}}
const required=(name:string)=>{const value=process.env[name];if(!value)throw new Error(`missing:${name}`);return value};
const assert=(condition:unknown,step:string)=>{if(!condition)throw new Error(`verification:${step}`)};
async function main(){const prisma=new PrismaClient(),app=await NestFactory.create(AppModule,{logger:false});const slug=`phase8-verification-${randomBytes(8).toString("hex")}`;let entityId:string|undefined;app.setGlobalPrefix("api/v1");app.use(json({limit:"256kb"}));app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true}));app.useGlobalInterceptors(new ResponseInterceptor());await app.listen(0,"127.0.0.1");const base=`${await app.getUrl()}/api/v1`,origin=required("ADMIN_FRONTEND_URL"),jar=new CookieJar();async function request(path:string,method="GET",body?:JsonRecord){const headers:Record<string,string>={Origin:origin};if(body)headers["Content-Type"]="application/json";const cookie=jar.header();if(cookie)headers.Cookie=cookie;const response=await fetch(`${base}${path}`,{method,headers,body:body?JSON.stringify(body):undefined});jar.apply(response);const payload=await response.json().catch(()=>({})) as {data?:unknown};return{response,data:payload.data}}
 try{const login=await request("/admin/auth/login","POST",{email:required("INITIAL_SUPER_ADMIN_EMAIL"),password:required("INITIAL_SUPER_ADMIN_PASSWORD"),rememberMe:false});assert(login.response.ok,"login");const created=await request("/admin/cms/services","POST",{data:{slug,name:"Phase 8 Verification",summary:"Draft one",content:{marker:"draft-one"},displayOrder:999}});assert(created.response.ok,"create-draft");entityId=(created.data as {id:string}).id;const preview=await request(`/admin/publishing/services/${entityId}/preview`,"POST");assert(preview.response.ok,"preview-context");const path=(preview.data as {path:string}).path,token=new URL(path,"http://local").searchParams.get("token");assert(token,"preview-token");const previewRead=await request(`/preview/services/${entityId}?token=${encodeURIComponent(token!)}`);assert(previewRead.response.ok&&(previewRead.data as {content:{marker:string}}).content.marker==="draft-one","preview-read");const first=await request(`/admin/publishing/services/${entityId}/publish`,"POST");assert(first.response.ok&&(first.data as {version:number}).version===1,"first-publish");const publicOne=await request(`/public/services/${slug}`);assert((publicOne.data as {content:{marker:string}}).content.marker==="draft-one","first-public-read");await request(`/admin/cms/services/${entityId}`,"PATCH",{data:{summary:"Draft two",content:{marker:"draft-two"}}});const stable=await request(`/public/services/${slug}`);assert((stable.data as {content:{marker:string}}).content.marker==="draft-one","stable-public-snapshot");const second=await request(`/admin/publishing/services/${entityId}/publish`,"POST");assert((second.data as {version:number}).version===2,"second-publish");const publicTwo=await request(`/public/services/${slug}`);assert((publicTwo.data as {content:{marker:string}}).content.marker==="draft-two","second-public-read");const revisions=await request(`/admin/publishing/services/${entityId}/revisions`);assert(Array.isArray(revisions.data)&&revisions.data.length===2,"revision-history");await request(`/admin/publishing/services/${entityId}/unpublish`,"POST");assert((await request(`/public/services/${slug}`)).response.status===404,"unpublish");assert(await prisma.activityLog.count({where:{entityId,action:{in:["CONTENT_PUBLISH","CONTENT_UNPUBLISH"]}}})===3,"audit-log");console.log("Phase 8 live publishing verification passed safely.")}
 finally{if(entityId){await prisma.contentRevision.deleteMany({where:{entityId}});await prisma.activityLog.deleteMany({where:{entityId}});await prisma.service.deleteMany({where:{id:entityId}})}await app.close();await prisma.$disconnect()}}
main().catch(error=>{const message=error instanceof Error?error.message:"verification";console.error(message.startsWith("missing:")?message:"Phase 8 verification failed safely.");process.exitCode=1});
