"use client";
import {ArrowRight,CheckCircle2} from "lucide-react";
import Link from "next/link";
import {Reveal} from "@/components/motion/reveal";
import {InnerHero} from "@/components/pages/inner-hero";
import {LinkButton} from "@/components/ui/button";
import {SectionHeading} from "@/components/ui/section-heading";
import {packageExperiences} from "@/content/packages";
export function PackagesPage(){return <><InnerHero eyebrow="Creative Packages" title="Packages built to grow your business" description="Focused creative solutions for educators, growing brands and businesses that need standout imagery."><LinkButton href="#package-categories" className="mt-9 rounded-full px-8">Choose a Package</LinkButton></InnerHero><section className="section" id="package-categories"><div className="site-container"><SectionHeading eyebrow="Package Categories" title="Choose the support you need" centered/><div className="category-grid">{packageExperiences.map((item,index)=><Reveal key={item.slug} delay={index*.08}><Link href={`/packages/${item.slug}`}><span>0{index+1}</span><h2>{item.name}</h2><p>{item.description}</p><strong>Explore packages <ArrowRight/></strong></Link></Reveal>)}</div><div className="package-stats">{[["3+","Years active"],["150+","Projects delivered"],["80+","Brand collaborations"],["20+","Package options"]].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div></section><section className="section service-dark"><div className="site-container"><SectionHeading eyebrow="Built Around You" title="Why choose our packages?" centered/><div className="benefit-grid">{[["Clear scope","Know what is included before work begins."],["Professional craft","Every deliverable follows the same high design standard."],["Flexible growth","Start focused and add custom support when needed."]].map(([title,description])=><Reveal key={title}><article><CheckCircle2/><h3>{title}</h3><p>{description}</p></article></Reveal>)}</div></div></section><section className="section"><div className="site-container"><SectionHeading eyebrow="How It Works" title="Four steps to move forward" centered/><div className="package-process">{["Select a category","Choose your tier","Share your brief","Create together"].map((step,index)=><Reveal key={step} delay={index*.06}><article><b>0{index+1}</b><h3>{step}</h3><p>Focused guidance keeps the process simple, transparent and collaborative.</p></article></Reveal>)}</div></div></section><section className="service-cta"><div className="site-container"><Reveal><p className="eyebrow">Custom Creative Support</p><h2>Can&apos;t find the perfect fit?</h2><p>Tell us what you need and we will shape a package around it.</p><LinkButton href="/get-a-quote?package=Custom" className="mt-8 rounded-full px-9">Build My Package</LinkButton></Reveal></div></section></>}
