"use client";
import {ArrowRight,CheckCircle2} from "lucide-react";
import Link from "next/link";
import {Reveal} from "@/components/motion/reveal";
import {PackageCard} from "@/components/packages/package-card";
import {InnerHero} from "@/components/pages/inner-hero";
import {LinkButton} from "@/components/ui/button";
import {SectionHeading} from "@/components/ui/section-heading";
import type {PackageExperience} from "@/content/packages";
export function PackageExperiencePage({experience}:{experience:PackageExperience}){return <><InnerHero eyebrow={experience.name} title={experience.title} description={experience.description}><LinkButton href="#packages" className="mt-9 rounded-full px-8">View Packages</LinkButton></InnerHero><section className="section" id="packages"><div className="site-container"><SectionHeading eyebrow="Choose Your Package" title="Simple options. Serious impact." centered/><div className="package-grid">{experience.tiers.filter(tier=>tier.active).sort((a,b)=>a.order-b.order).map((tier,index)=><PackageCard tier={tier} index={index} key={tier.name}/>)}</div></div></section><section className="section service-dark"><div className="site-container"><SectionHeading eyebrow="Why It Matters" title={`Why choose ${experience.name.toLowerCase()}?`} centered/><div className="benefit-grid">{experience.benefits.map((benefit,index)=><Reveal key={benefit.title} delay={index*.07}><article><CheckCircle2/><h3>{benefit.title}</h3><p>{benefit.description}</p></article></Reveal>)}</div></div></section><section className="section"><div className="site-container"><SectionHeading eyebrow="How It Works" title="A clear path from brief to delivery" centered/><div className="package-process">{["Choose your package","Share your goals","Review the creative","Launch with confidence"].map((step,index)=><Reveal key={step} delay={index*.06}><article><b>0{index+1}</b><h3>{step}</h3><p>{["Select the option that fits your current stage.","Complete the quote brief so we understand the context.","Collaborate through focused feedback rounds.","Receive organised files ready for real-world use."][index]}</p></article></Reveal>)}</div></div></section><section className="service-cta"><div className="site-container"><Reveal><p className="eyebrow">Need something different?</p><h2>Build a custom package around your goals.</h2><LinkButton href={`/get-a-quote?service=${encodeURIComponent(experience.name)}&package=Custom`} className="mt-8 rounded-full px-9">Request a Custom Package</LinkButton><Link href="/contact" className="custom-contact">Talk to our team <ArrowRight/></Link></Reveal></div></section></>}
