import {Injectable,NotFoundException} from "@nestjs/common";
import {ContentStatus,Prisma} from "@prisma/client";
import {PrismaService} from "../prisma/prisma.service";
import type {PackageQueryDto,PortfolioQueryDto} from "./public-content.dto";
@Injectable()
export class PublicContentService{
 constructor(private readonly prisma:PrismaService){}
 async page(slug:string){const item=await this.prisma.page.findFirst({where:{slug,status:ContentStatus.PUBLISHED,deletedAt:null},select:{slug:true,title:true,sections:{where:{isEnabled:true},orderBy:{displayOrder:"asc"},select:{key:true,kind:true,content:true,displayOrder:true}},seo:{select:{title:true,description:true,canonicalUrl:true,openGraph:true}}}});if(!item)throw new NotFoundException("Page not found");return item}
 services(){return this.prisma.service.findMany({where:{status:ContentStatus.PUBLISHED,deletedAt:null},orderBy:{displayOrder:"asc"},select:{slug:true,name:true,summary:true,content:true,displayOrder:true,seo:{select:{title:true,description:true,canonicalUrl:true,openGraph:true}}}})}
 async service(slug:string){const item=await this.prisma.service.findFirst({where:{slug,status:ContentStatus.PUBLISHED,deletedAt:null},select:{slug:true,name:true,summary:true,content:true,displayOrder:true,seo:{select:{title:true,description:true,canonicalUrl:true,openGraph:true}}}});if(!item)throw new NotFoundException("Service not found");return item}
 async portfolio(query:PortfolioQueryDto){const where:Prisma.PortfolioProjectWhereInput={status:ContentStatus.PUBLISHED,deletedAt:null,category:query.category?{slug:query.category,isActive:true}:{isActive:true}};const [items,total]=await this.prisma.$transaction([this.prisma.portfolioProject.findMany({where,skip:(query.page-1)*query.limit,take:query.limit,orderBy:{displayOrder:"asc"},select:{slug:true,title:true,clientName:true,summary:true,content:true,displayOrder:true,category:{select:{slug:true,name:true}}}}),this.prisma.portfolioProject.count({where})]);return {items,pagination:{page:query.page,limit:query.limit,total,pages:Math.ceil(total/query.limit)}}}
 async project(slug:string){const item=await this.prisma.portfolioProject.findFirst({where:{slug,status:ContentStatus.PUBLISHED,deletedAt:null},select:{slug:true,title:true,clientName:true,summary:true,content:true,category:{select:{slug:true,name:true}},service:{select:{slug:true,name:true}},seo:{select:{title:true,description:true,canonicalUrl:true,openGraph:true}}}});if(!item)throw new NotFoundException("Portfolio project not found");return item}
 packages(query:PackageQueryDto){return this.prisma.packageCategory.findMany({where:{isActive:true,...(query.category?{slug:query.category}:{})},orderBy:{displayOrder:"asc"},select:{slug:true,name:true,headline:true,description:true,content:true,packages:{where:{isActive:true,status:ContentStatus.PUBLISHED},orderBy:{displayOrder:"asc"},select:{slug:true,name:true,subtitle:true,description:true,price:true,currency:true,priceLabel:true,isPopular:true,displayOrder:true,features:{orderBy:{displayOrder:"asc"},select:{label:true,displayOrder:true}}}}}})}
 async package(slug:string){const item=await this.prisma.package.findFirst({where:{slug,isActive:true,status:ContentStatus.PUBLISHED,category:{isActive:true}},select:{slug:true,name:true,subtitle:true,description:true,price:true,currency:true,priceLabel:true,isPopular:true,displayOrder:true,category:{select:{slug:true,name:true,headline:true,description:true}},features:{orderBy:{displayOrder:"asc"},select:{label:true,displayOrder:true}}}});if(!item)throw new NotFoundException("Package not found");return item}
 testimonials(){return this.prisma.testimonial.findMany({where:{status:ContentStatus.PUBLISHED},orderBy:{displayOrder:"asc"},select:{clientName:true,clientRole:true,company:true,quote:true,rating:true,displayOrder:true}})}
 settings(){return this.prisma.siteSetting.findMany({where:{isPublic:true},orderBy:{key:"asc"},select:{key:true,value:true}})}
}
