import { Mail, MapPin, Phone, Clock3 } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";
import { InfoCard } from "@/components/pages/info-card";
import { InnerHero } from "@/components/pages/inner-hero";
import { LinkButton } from "@/components/ui/button";
import { SectionHeading } from "@/components/ui/section-heading";
import { aboutContent } from "@/content/about";

export function AboutPage() { const h=aboutContent.hero; return <>
  <InnerHero eyebrow={h.eyebrow} title={h.title} accent={h.accent} description={h.description}><h2 className="inner-hero-tail">{h.tail}</h2><LinkButton href="/portfolio" className="mt-10 rounded-full px-9 uppercase tracking-wider">Explore our portfolio</LinkButton><div className="hero-badges">{aboutContent.badges.map(({label,icon:Icon})=><span key={label}><Icon/>{label}</span>)}</div></InnerHero>
  <section className="section bg-charcoal"><div className="site-container about-split"><Reveal><p className="eyebrow">Who We Are</p><h2 className="section-title mt-7 max-w-xl">A Creative Studio Built on Passion &amp; Purpose</h2><div className="prose-copy"><p>Founded in 2022 and proudly rooted in Sri Lanka, Design Koolama (Pvt) Ltd. was born from a vision to bring world-class creative design to businesses across the island and beyond. We specialize in branding, graphic design, and digital experiences.</p><p>At the heart of everything we do is a commitment to our clients. We are detail-oriented, strategy-driven, and deeply passionate about delivering design that makes a measurable impact.</p></div></Reveal><div className="grid gap-5">{aboutContent.facts.map(({icon,title,description})=><Reveal key={title}><InfoCard icon={icon} title={title} accent>{description}</InfoCard></Reveal>)}</div></div></section>
  <section className="section bg-black"><div className="site-container"><p className="eyebrow text-center">Founder&apos;s Message</p><div className="founder-grid"><Reveal><div className="founder-card"><div className="founder-avatar">DP</div><h2>Dineth Pabasara</h2><p>Founder &amp; Creative Designer</p><span>Leading creative strategy and design excellence at Design Koolama</span></div></Reveal><Reveal><div className="founder-message"><span className="founder-quote">“</span><h2 className="section-title">Welcome to Design Koolama</h2><p>I founded this studio with a single vision — to bring world-class creative design to Sri Lankan businesses and beyond. Great design is not just aesthetics; it is a powerful business tool that communicates your brand&apos;s story, values, and vision.</p><p>Every project we take on is crafted with care, strategy, and creativity at its core. Thank you for choosing to be part of our journey.</p><strong>Dineth Pabasara</strong><small>Founder, Design Koolama</small></div></Reveal></div></div></section>
  <section className="section bg-charcoal"><div className="site-container"><SectionHeading eyebrow="Our Foundation" title="Our Mission, Vision & Core Values" centered/><div className="foundation-grid">{aboutContent.foundation.map(({icon,title,description})=><InfoCard key={title} icon={icon} title={title}>{description}</InfoCard>)}</div><p className="values-label">Core Values</p><div className="values-grid">{aboutContent.values.map(({icon,title,description})=><InfoCard key={title} icon={icon} title={title}>{description}</InfoCard>)}</div></div></section>
  <section className="section bg-black"><div className="site-container contact-advantage"><div><SectionHeading eyebrow="Our Location" title="Find Us & Get In Touch"/><div className="mt-10 grid gap-4"><InfoCard icon={MapPin} title="Office Address">No. 460, Thalawathugoda Road, Madiwela, Sri Jayawardenepura Kotte, Colombo, Sri Lanka</InfoCard><InfoCard icon={Mail} title="Email Us">hello@designkoolama.com</InfoCard><InfoCard icon={Phone} title="Call Us">+94 77 000 0000</InfoCard><InfoCard icon={Clock3} title="Operating Hours">Mon – Fri · 9:00 AM – 6:00 PM</InfoCard></div></div><div><SectionHeading eyebrow="Our Advantage" title="Why Work With Us?"/><div className="advantage-list">{aboutContent.advantages.map(({title,icon:Icon})=><div key={title}><span><Icon/></span><h3>{title}</h3><p>Reliable, considered creative partnership built around your goals and timeline.</p></div>)}</div><LinkButton href="/get-a-quote" className="mt-9 w-full uppercase tracking-widest">Get a free quote</LinkButton></div></div></section>
  </>; }
