export type RouteUiContent = {
  portfolio: { heroEyebrow:string;heroTitle:string;heroAccent:string;heroDescription:string;overviewLabel:string;challengeLabel:string;solutionLabel:string;resultsLabel:string;galleryLabel:string;previousLabel:string;nextLabel:string;relatedLabel:string;ctaEyebrow:string;ctaTitle:string;ctaButton:string;ctaHref:string };
  services: { startButton:string;overviewLabel:string;quoteButton:string;processEyebrow:string;processTitle:string;showcaseEyebrow:string;showcaseSuffix:string;relatedEyebrow:string;relatedTitle:string;ctaEyebrow:string;ctaTitle:string;ctaButton:string };
  packages: { heroEyebrow:string;heroTitle:string;heroDescription:string;heroButton:string;categoriesEyebrow:string;categoriesTitle:string;exploreLabel:string;stats:Array<{value:string;label:string;visible:boolean;order:number}>;benefitsEyebrow:string;benefitsTitle:string;benefits:Array<{title:string;description:string;visible:boolean;order:number}>;processEyebrow:string;processTitle:string;steps:Array<{title:string;description:string;visible:boolean;order:number}>;customEyebrow:string;customTitle:string;customDescription:string;customButton:string };
};
export const routeUiContent:RouteUiContent={
  portfolio:{heroEyebrow:"Our Work",heroTitle:"Our",heroAccent:"Portfolio",heroDescription:"Explore selected brand systems, campaigns, packaging, merchandise, and dimensional design crafted to make businesses stand out.",overviewLabel:"Project Overview",challengeLabel:"The Challenge",solutionLabel:"Our Solution",resultsLabel:"Results",galleryLabel:"Project Gallery",previousLabel:"Previous project",nextLabel:"Next project",relatedLabel:"Related Projects",ctaEyebrow:"Have a project in mind?",ctaTitle:"Let's create something extraordinary.",ctaButton:"Start a Project",ctaHref:"/get-a-quote"},
  services:{startButton:"Start a Project",overviewLabel:"Service Overview",quoteButton:"Request a Quote",processEyebrow:"Our Process",processTitle:"From first thought to final form",showcaseEyebrow:"Visual Showcase",showcaseSuffix:"in action",relatedEyebrow:"Explore More",relatedTitle:"Related Services",ctaEyebrow:"Have a project in mind?",ctaTitle:"Let's create something remarkable.",ctaButton:"Get a Free Quote"},
  packages:{heroEyebrow:"Creative Packages",heroTitle:"Packages built to grow your business",heroDescription:"Focused creative solutions for educators, growing brands and businesses that need standout imagery.",heroButton:"Choose a Package",categoriesEyebrow:"Package Categories",categoriesTitle:"Choose the support you need",exploreLabel:"Explore packages",stats:[["3+","Years active"],["150+","Projects delivered"],["80+","Brand collaborations"],["20+","Package options"]].map(([value,label],order)=>({value,label,visible:true,order})),benefitsEyebrow:"Built Around You",benefitsTitle:"Why choose our packages?",benefits:[{title:"Clear scope",description:"Know what is included before work begins."},{title:"Professional craft",description:"Every deliverable follows the same high design standard."},{title:"Flexible growth",description:"Start focused and add custom support when needed."}].map((item,order)=>({...item,visible:true,order})),processEyebrow:"How It Works",processTitle:"Four steps to move forward",steps:["Select a category","Choose your tier","Share your brief","Create together"].map((title,order)=>({title,description:"Focused guidance keeps the process simple, transparent and collaborative.",visible:true,order})),customEyebrow:"Custom Creative Support",customTitle:"Can't find the perfect fit?",customDescription:"Tell us what you need and we will shape a package around it.",customButton:"Build My Package"}
};
