"use client";
import { Activity, ExternalLink, FileText, FolderKanban, Image, LayoutDashboard, LogOut, Mail, Menu, MessageSquareQuote, Package, Settings, Shield, Sparkles, Star, Tags, UserRound, X } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { adminApi, type AdminProfile } from "@/lib/admin-api";
const links=[{href:"/admin/dashboard",label:"Dashboard",icon:LayoutDashboard},{href:"/admin/profile",label:"Profile",icon:UserRound},{href:"/admin/security",label:"Security",icon:Shield}];
const cmsLinks=[{href:"/admin/content",label:"Website content",icon:FileText},{href:"/admin/services",label:"Services",icon:Sparkles},{href:"/admin/portfolio",label:"Portfolio",icon:FolderKanban},{href:"/admin/portfolio-categories",label:"Portfolio categories",icon:Tags},{href:"/admin/packages",label:"Packages",icon:Package},{href:"/admin/package-categories",label:"Package categories",icon:Tags},{href:"/admin/media",label:"Media library",icon:Image},{href:"/admin/testimonials",label:"Testimonials",icon:Star},{href:"/admin/quotes",label:"Quote requests",icon:MessageSquareQuote},{href:"/admin/messages",label:"Contact messages",icon:Mail},{href:"/admin/settings",label:"Website settings",icon:Settings},{href:"/admin/activity",label:"Activity log",icon:Activity}];
export function AdminShell({children}:{children:React.ReactNode}){
 const path=usePathname(),router=useRouter();const [admin,setAdmin]=useState<AdminProfile|null>(null);const [open,setOpen]=useState(false);const [checking,setChecking]=useState(true);
 useEffect(()=>{let active=true;adminApi.me().then(value=>{if(active)setAdmin(value)}).catch(()=>router.replace(`/admin/login?returnTo=${encodeURIComponent(path)}`)).finally(()=>{if(active)setChecking(false)});return()=>{active=false}},[path,router]);
 async function logout(){try{await adminApi.logout()}finally{router.replace("/admin/login");router.refresh()}}
 if(checking)return <div className="admin-screen-state" role="status">Verifying secure session…</div>;
 if(!admin)return <div className="admin-screen-state" role="status">Redirecting to sign in…</div>;
 const renderLink=({href,label,icon:Icon}:{href:string;label:string;icon:typeof LayoutDashboard})=><Link key={href} href={href} onClick={()=>setOpen(false)} aria-current={path===href?"page":undefined}><Icon/>{label}</Link>;
 return <div className="admin-layout"><aside className={open?"admin-sidebar is-open":"admin-sidebar"}><div className="admin-sidebar-head"><Link className="admin-brand" href="/admin/dashboard">DesignKoolama<span>•</span></Link><button className="admin-close" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div><nav aria-label="Admin navigation">{links.map(renderLink)}<details open><summary>Content management</summary>{cmsLinks.map(renderLink)}</details><Link href="/" target="_blank"><ExternalLink/>View website</Link></nav><div className="admin-account"><span>{admin.displayName}</span><small>{admin.roles.join(", ")}</small><button onClick={logout}><LogOut/> Sign out</button></div></aside>{open&&<button className="admin-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<section className="admin-workspace"><header className="admin-topbar"><button onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><div><strong>{admin.displayName}</strong><span>{admin.email}</span></div></header><div className="admin-content">{children}</div></section></div>
}
