"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { adminApi } from "@/lib/admin-api";

function Message({ text, error = false }: { text: string; error?: boolean }) { return text ? <p role={error ? "alert" : "status"} className={error ? "admin-error" : "admin-success"}>{text}</p> : null; }
export function LoginForm() {
  const router = useRouter(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [show,setShow]=useState(false);
  useEffect(()=>{let active=true;adminApi.me().then(()=>{if(active)router.replace("/admin/dashboard")}).catch(()=>undefined);return()=>{active=false}},[router]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const data=new FormData(event.currentTarget); try { await adminApi.login(String(data.get("email")),String(data.get("password")),data.get("rememberMe")==="on"); router.replace("/admin/dashboard"); router.refresh(); } catch(error){setMessage(error instanceof Error?error.message:"Sign in failed");} finally{setBusy(false);} }
  return <form className="admin-form" onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="username" required/></label><label>Password<span className="admin-password"><input name="password" type={show?"text":"password"} autoComplete="current-password" required/><button type="button" onClick={()=>setShow(value=>!value)} aria-pressed={show}>{show?"Hide":"Show"}</button></span></label><label className="admin-check"><input name="rememberMe" type="checkbox"/> Keep me signed in on this device</label><Message text={message} error/><button disabled={busy}>{busy?"Signing in…":"Sign in"}</button><Link href="/admin/forgot-password">Forgot your password?</Link></form>;
}
export function ForgotForm() { const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const data=new FormData(event.currentTarget);const result=await adminApi.forgot(String(data.get("email")));setMessage(result.message);}catch{setMessage("If an eligible account exists, reset instructions will be sent.");}finally{setBusy(false)}} return <form className="admin-form" onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="email" required/></label><Message text={message}/><button disabled={busy}>{busy?"Submitting…":"Request reset"}</button><Link href="/admin/login">Return to sign in</Link></form> }
export function ResetForm(){const params=useSearchParams();const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const data=new FormData(event.currentTarget);const password=String(data.get("password"));if(password!==data.get("confirm")){setMessage("Passwords do not match");setBusy(false);return}try{await adminApi.reset(params.get("token")??"",password);router.replace("/admin/login?reset=complete");}catch(error){setMessage(error instanceof Error?error.message:"Reset link is invalid or expired");}finally{setBusy(false)}}return <form className="admin-form" onSubmit={submit}><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} required/></label><label>Confirm password<input name="confirm" type="password" autoComplete="new-password" minLength={12} required/></label><p className="admin-hint">Use 12+ characters with uppercase, lowercase, number and symbol.</p><Message text={message} error/><button disabled={busy}>{busy?"Updating…":"Set new password"}</button></form>}
