"use client";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRight, ChevronLeft, ChevronRight } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { EmptyState } from "@/components/feedback/states";
import { ProjectArt } from "@/components/portfolio/project-art";
import { portfolioCategories, portfolioProjects, type PortfolioCategory } from "@/content/portfolio";

const pageSize=6;
export function PortfolioBrowser(){const [category,setCategory]=useState<PortfolioCategory>("All");const [page,setPage]=useState(1);const reduce=useReducedMotion();const filtered=useMemo(()=>category==="All"?portfolioProjects:portfolioProjects.filter(p=>p.category===category),[category]);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const shown=filtered.slice((page-1)*pageSize,page*pageSize);const choose=(value:PortfolioCategory)=>{setCategory(value);setPage(1)};return <><div className="filter-bar" role="group" aria-label="Filter projects by category">{portfolioCategories.map(value=><button type="button" aria-pressed={category===value} onClick={()=>choose(value)} key={value}>{value}</button>)}</div>{shown.length===0?<EmptyState title="No projects in this category yet"/>:<motion.div layout className="portfolio-grid"><AnimatePresence mode="popLayout">{shown.map(project=><motion.article layout initial={reduce?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} key={project.slug} className="portfolio-list-card"><ProjectArt tone={project.tone}/><div><span>{project.category}</span><h2>{project.title}</h2><p>{project.description}</p><Link href={`/portfolio/${project.slug}`}>Explore More <ArrowRight/></Link></div></motion.article>)}</AnimatePresence></motion.div>}<nav className="pagination" aria-label="Portfolio pagination"><button disabled={page===1} onClick={()=>setPage(v=>v-1)} aria-label="Previous page"><ChevronLeft/></button>{Array.from({length:pages},(_,index)=>index+1).map(value=><button aria-current={page===value?"page":undefined} onClick={()=>setPage(value)} key={value}>{value}</button>)}<button disabled={page===pages} onClick={()=>setPage(v=>v+1)} aria-label="Next page"><ChevronRight/></button></nav></>}
