import { expect, test, type Page } from "@playwright/test";
const profile={id:"cms-admin",email:"admin@example.test",displayName:"CMS Admin",status:"ACTIVE",lastLoginAt:null,roles:["SUPER_ADMIN"]};
async function mockCms(page:Page){let rows=[{id:"service-1",name:"Brand identity",slug:"brand-identity",summary:"Brand systems",status:"PUBLISHED",displayOrder:1,content:{}}];await page.route("**/api/v1/admin/**",async route=>{const url=new URL(route.request().url()),method=route.request().method();if(url.pathname.endsWith("/auth/me"))return route.fulfill({json:{data:profile}});if(url.pathname.includes("/cms/")){const quote=url.pathname.includes("/cms/quotes");if(method==="GET")return route.fulfill({json:{data:quote?[{id:"quote-1",fullName:"Test Client",status:"NEW"}]:rows}});if(method==="POST"){const body=route.request().postDataJSON();const saved={id:"service-2",...body.data};rows=[...rows,saved];return route.fulfill({json:{data:saved}})}if(method==="PATCH")return route.fulfill({json:{data:{id:"quote-1",fullName:"Test Client",status:"REPLIED"}}});if(method==="DELETE")return route.fulfill({json:{data:{archived:true}}})}return route.fulfill({json:{data:{}}})})}
test("CMS navigation exposes planned Phase 7 modules",async({page})=>{await mockCms(page);await page.goto("/admin/services");await expect(page.getByRole("link",{name:"Website content"})).toBeVisible();await expect(page.getByRole("link",{name:"Media library"})).toBeVisible();await expect(page.getByRole("link",{name:"Activity log"})).toBeVisible()});
test("service records can be searched and opened for editing",async({page})=>{await mockCms(page);await page.goto("/admin/services");const record=page.getByRole("button",{name:/Brand identity/});await expect(record).toBeVisible();await page.getByPlaceholder("Search records").fill("brand");await record.click();await expect(page.getByRole("heading",{name:"Edit record"})).toBeVisible();await expect(page.getByLabel("Summary")).toHaveValue("Brand systems")});
test("service form validates structured JSON without sending invalid data",async({page})=>{await mockCms(page);await page.goto("/admin/services");await page.getByRole("button",{name:"Add record"}).click();await page.getByLabel("Name").fill("Strategy");await page.getByLabel("Slug").fill("strategy");await page.getByLabel("Summary").fill("Strategy service");await page.getByLabel("Content (JSON)").fill("not json");await page.getByRole("button",{name:"Save draft"}).click();await expect(page.locator("p.admin-error[role=alert]")).toContainText("valid JSON")});
test("quote request status can be triaged",async({page})=>{await mockCms(page);await page.goto("/admin/quotes");const request=page.waitForRequest(value=>value.method()==="PATCH"&&value.url().includes("/cms/quotes/quote-1/status"));await page.getByRole("combobox").first().selectOption("REPLIED");expect((await request).postDataJSON()).toEqual({status:"REPLIED"})});
test("CMS routes remain noindex",async({page})=>{await mockCms(page);await page.goto("/admin/services");await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content",/noindex/)});
for(const width of [320,768,1440])test(`CMS service manager has no horizontal overflow at ${width}px`,async({page})=>{await mockCms(page);await page.setViewportSize({width,height:900});await page.goto("/admin/services");await expect(page.getByRole("heading",{name:"Services"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);if(width!==768)await page.screenshot({path:`test-results/screenshots/phase7-cms-services-${width}.png`,fullPage:true})});
