import {expect,test,type Page} from "@playwright/test";
const widths=[320,375,430,768,1024,1280,1440,1920] as const;
const routes=[
  ["brand-identity","/services/brand-identity",/Brand Identity/i],["print-advertising","/services/print-advertising",/Print Advertising/i],["social-media-design","/services/social-media-design",/Social Media Design/i],["packaging-design","/services/packaging-design",/Packaging Design/i],["merchandise-design","/services/merchandise-design",/Merchandise Design/i],["3d-design","/services/3d-design",/3D Design/i],
  ["packages","/packages",/Packages built to grow your business/i],["tutor-packages","/packages/tutor",/Build your tutor brand/i],["branding-packages","/packages/branding",/Build a brand that people remember/i],["photography-packages","/packages/photography",/Capture your brand/i]
] as const;
async function capture(page:Page,name:string,width:number){if(width!==375&&width!==1440)return;for(const section of await page.locator("main > section").all()){await section.scrollIntoViewIfNeeded();await page.waitForTimeout(35)}await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(200);await page.screenshot({path:`test-results/screenshots/phase4-${name}-${width}.png`,fullPage:true})}
for(const [name,path,heading] of routes){for(const width of widths){test(`${name} at ${width}px`,async({page})=>{const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));await page.setViewportSize({width,height:width<768?900:1000});const response=await page.goto(path,{waitUntil:"domcontentloaded"});expect(response?.status()).toBe(200);await expect(page.getByRole("heading",{name:heading}).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);expect(errors).toEqual([]);await capture(page,name,width)})}}
test("invalid service route uses not found experience",async({page})=>{await page.goto("/services/not-a-service");await expect(page.getByRole("heading",{name:"This idea wandered off."})).toBeVisible()});
test("service links navigate to quote with preselection",async({page})=>{await page.goto("/services/brand-identity");await page.getByRole("link",{name:"Start a Project"}).click();await expect(page).toHaveURL(/service=Branding/);await expect(page.getByLabel("Service Required")).toHaveValue("Branding & Identity")});
test("package category and CTA preserve selection",async({page})=>{await page.goto("/packages");await page.getByRole("link",{name:/Tutor Packages/}).click();await expect(page).toHaveURL(/\/packages\/tutor/);await page.getByRole("link",{name:"Choose Growth"}).click();await expect(page).toHaveURL(/package=Growth/);await expect(page.getByLabel("Service Required")).toHaveValue("Social Media Design");await expect(page.getByLabel("Project Details")).toHaveValue(/Growth package/)});
test("phase 4 mobile menu remains accessible",async({page})=>{await page.setViewportSize({width:375,height:812});await page.goto("/packages/branding");await page.getByRole("button",{name:"Open navigation"}).click();await expect(page.getByRole("navigation",{name:"Mobile navigation"})).toBeVisible();await page.keyboard.press("Escape");await expect(page.getByRole("navigation",{name:"Mobile navigation"})).toBeHidden()});
test("phase 4 internal links resolve",async({page,request})=>{for(const [,path] of routes){await page.goto(path);const links=await page.locator('main a[href^="/"]').evaluateAll(nodes=>[...new Set(nodes.map(node=>(node as HTMLAnchorElement).getAttribute("href")!).filter(href=>!href.startsWith("/contact")&&!href.startsWith("/privacy")&&!href.startsWith("/terms")))]);for(const href of links){const response=await request.get(href);expect(response.status(),`${path} -> ${href}`).toBeLessThan(400)}}});
