import { expect, test, type Page } from "@playwright/test";

const widths=[320,375,430,768,1024,1280,1440,1920] as const;
const routes=[{name:"about",path:"/about",heading:/Designing Brands That/i},{name:"contact",path:"/contact",heading:/Contact Us/i},{name:"quote",path:"/get-a-quote",heading:/Get a Quote/i},{name:"portfolio",path:"/portfolio",heading:/Our Portfolio/i}] as const;

async function revealAndCapture(page:Page,name:string,width:number){for(const section of await page.locator("main > section").all()){await section.scrollIntoViewIfNeeded();await page.waitForTimeout(50)}await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(300);await page.screenshot({path:`test-results/screenshots/phase3-${name}-${width}.png`,fullPage:true})}

for(const route of routes){for(const width of widths){test(`${route.name} at ${width}px`,async({page})=>{const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));await page.setViewportSize({width,height:width<768?900:1000});await page.goto(route.path,{waitUntil:"domcontentloaded"});await expect(page.getByRole("heading",{name:route.heading}).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);expect(errors).toEqual([]);await revealAndCapture(page,route.name,width)})}}

test("contact form validation and FAQ",async({page})=>{await page.goto("/contact");await page.getByRole("button",{name:"Send Message"}).click();await expect(page.getByText("Enter your full name").first()).toBeVisible();const second=page.getByRole("button",{name:"Do you work with international clients?"});await second.click();await expect(second).toHaveAttribute("aria-expanded","true")});
test("quote validates and explains deferred attachments",async({page})=>{await page.goto("/get-a-quote");await expect(page.getByText(/Attachment uploads are deferred/i)).toBeVisible();await page.getByRole("button",{name:"Submit Request"}).click();await expect(page.getByText("Choose a service")).toBeVisible()});
test("portfolio filtering and detail navigation",async({page})=>{await page.goto("/portfolio");await page.getByRole("button",{name:"3D Design"}).click();await expect(page.getByRole("heading",{name:"Forma Identity"})).toBeVisible();await expect(page.getByRole("heading",{name:"Nexus Rebrand"})).toBeHidden();const detailLink=page.getByRole("link",{name:/Explore More/});await expect(detailLink).toHaveAttribute("href","/portfolio/forma-identity");await Promise.all([page.waitForURL(/forma-identity/),detailLink.click()]);await expect(page.getByRole("heading",{name:"Forma Identity"})).toBeVisible()});
test("invalid portfolio slug returns custom not found",async({page})=>{await page.goto("/portfolio/not-a-project");await expect(page.getByRole("heading",{name:"This idea wandered off."})).toBeVisible()});
test("internal mobile navigation",async({page})=>{await page.setViewportSize({width:375,height:812});await page.goto("/about");await page.getByRole("button",{name:"Open navigation"}).click();await expect(page.getByRole("navigation",{name:"Mobile navigation"})).toBeVisible();await page.keyboard.press("Escape");await expect(page.getByRole("navigation",{name:"Mobile navigation"})).toBeHidden()});
